# Generated by Django 2.0.1 on 2018-01-11 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('q_text', models.CharField(max_length=200)),
                ('a_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('publisher', models.CharField(max_length=200)),
                ('event_code', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chains.Story'),
        ),
        migrations.AddField(
            model_name='question',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chains.Sentence'),
        ),
    ]
